config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, except: [:show,:edit,:update]
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root :to => 'welcome#index'
  root 'welcome#index'

  resources :friendships
  resources :users, only: [:show]

  get 'my_portfolio', to: "users#my_portfolio"
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
  delete 'remove_friend', to: "users#remove_friend"
  controller :welcome do

  end
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :users, through: :user_stocks
  has_many :user_stocks
  # Use net/http to access the API
  require 'net/http'
  require 'json'
  require 'ostruct'

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = Stock.api_lookup(ticker_symbol)
    return nil unless looked_up_stock.present?

    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end

  def price
    stock_data = Stock.api_lookup(ticker)
    return 'Unavailable' unless stock_data.present?

    closing_price = stock_data.close
    return "#{closing_price} (Closing)" if closing_price

    opening_price = stock_data.open
    return "#{opening_price} (Opening)" if opening_price
    'Unavailable'
  end

  private

  def self.api_lookup(ticker_symbol)

    api_url = 'https://www.alphavantage.co/query'

    query = {
      function: 'TIME_SERIES_INTRADAY',
      interval: '1min',
      symbol: ticker_symbol,
      apikey: 'B95P77JMNZ0OFH0N'
    }.to_query

    # Combine the API URL and the query to get the full URL
    url = "#{api_url}?#{query}"

    begin # Use error handling
      # Send API request and parse JSON response.
      uri = URI(url)
      response = Net::HTTP.get(uri)
      data = JSON.parse(response)

      # Get the actual historical data
      historical_data = data['Time Series (1min)']

      # Get the most recent data
      recent_data = historical_data.first
      # The actual data hash is in the second item.
      recent_data = recent_data.second

      # Extract desired information into a struct to avoid hash notation.
      OpenStruct.new({
        open: recent_data['1. open'].try(:to_f),
        close: recent_data['4. close'].try(:to_f),
        high: recent_data['2. high'].try(:to_f),
        low: recent_data['3. low'].try(:to_f),
        symbol: data['Meta Data']["2. Symbol"],
      })
    # Rescue any network related errors
    rescue Timeout::Error, Errno::EINVAL, Errno::ECONNRESET, EOFError,
       Net::HTTPBadResponse, Net::HTTPHeaderSyntaxError, Net::ProtocolError => e
       # Add any network error handling logic here
       puts "#{e.class} #{e.message}"
       nil # Lookup failed, return nothing
    # Rescue JSON Parse error, likely caused by an internal issue or slow response.
    rescue JSON::ParserError => e
      nil
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_from_lookup(params[:stock])
    end

    if @stock
      # render json: @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end
end

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Current Price</th>
    </tr>
    <% if @user.id == current_user %>
    <th>Actions</th>
    <% end %>
  </thead>
  <tbody>
    <% @user.stocks.each do |user_stock| %>
    <tr>
      <td><%= user_stock.ticker %></td>
      <td><%= user_stock.price %></td>
      <% if current_user.id == @user.id %>
      <td>
        <%= link_to "Delete", user_stock_path(UserStock.where(stock_id: user_stock.id, user_id: @user.id).first), method: :delete, :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-xs btn-danger' %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">
  <h3>Search for Stocks</h3>
  <%= form_tag search_stocks_path, remote: true, method: :get, id:'stock-lookup-form' do %>
    <div class="from-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], placeholder:'Stock Ticker Symbol', autofocus: true, class:'form-control search-box input-lg' %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do%>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @stock %>
    <div id="stock-lookup-results" class="well results-block">
      <strong>Symbol: </strong><%= @stock.ticker%>
      <strong>Price: </strong><%= @stock.price%>
      <% if current_user.can_add_stock?(@stock.ticker) %>
        <%= link_to "Add to my stock", user_stocks_path(user: current_user, stock_ticker: @stock.ticker, stock_id: @stock.id ? @stock.id : ''), class: 'btn btn-xs btn-success', method: :post %>
      <% else %>
        <span class="label label-default">
          Stock cant be added because you have already added
          <% if !current_user.under_stock_limit? %>
          10 stocks
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker) %>
          this stock
          <% end %>
        </span>
      <% end %>
    </div>

  <% end %>
  <div id="stock-lookup-errors"></div>
</div>